from typing import Dict, List, Any, Optional, Union, Callable
from tascpy.core.step import Step
from tascpy.core.column import Column
from tascpy.core.result import AnalysisResult
from tascpy.analytics.typing.core import CoreCollectionOperations
from tascpy.visualization.plotters.core.plotter import CorePlotter

class ColumnCollection:
    domain: str
    columns: Dict[str, Column]
    metadata: Dict[str, Any]
    
    @property
    def step(self) -> Step: ...
    
    @step.setter
    def step(self, value: Union[Step, List[Any]]) -> None: ...
    
    @property
    def ops(self) -> CoreCollectionOperations: ...
    
    @property
    def plot(self) -> CorePlotter: ...
    
    @property
    def results(self) -> Dict[str, AnalysisResult]: ...
    
    @property
    def steps(self) -> List[Any]: ...
    
    @property
    def date(self) -> List[str]: ...
    
    @property
    def time(self) -> List[str]: ...

    def __init__(
        self,
        step: Union[Step, List[Any], None],
        columns: Dict[str, Union[Column, List[Any]]],
        metadata: Optional[Dict[str, Any]] = ...,
        auto_detect_types: bool = ...
    ) -> None: ...

    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[str, int, slice]) -> Union["ColumnCollection", Column, Dict[str, Any]]: ...
    def __repr__(self) -> str: ...
    
    def clone(self) -> "ColumnCollection": ...
    
    def add_column(self, name: str, column: Union[Column, List[Any]]) -> "ColumnCollection": ...
    def remove_column(self, name: str) -> "ColumnCollection": ...
    def harmonize_length(self) -> None: ...
    def add_result(self, result: AnalysisResult) -> "ColumnCollection": ...
    def get_result(self, name: str) -> AnalysisResult: ...
    def keys(self) -> List[str]: ...
    
    def head(self, n: int = ...) -> "ColumnCollection": ...
    def tail(self, n: int = ...) -> "ColumnCollection": ...
    
    def describe(self, detail: bool = ...) -> Dict[str, Dict[str, Any]]: ...
    def apply(self, func: Callable[[List[Any]], List[Any]]) -> "ColumnCollection": ...
    def auto_detect_column_types(self) -> "ColumnCollection": ...
    
    def get_date_time(self) -> tuple[List[str], List[str]]: ...
    def find_nearest_step(self, value: Any) -> tuple[int, Any]: ...
    
    def max(self) -> Dict[str, Any]: ...
    def min(self) -> Dict[str, Any]: ...
    def mean(self) -> Dict[str, Optional[float]]: ...
    def ptp(self) -> Dict[str, Any]: ...
    def first_valid_index(self) -> Dict[str, Optional[int]]: ...
    def first_invalid_index(self) -> Dict[str, Optional[int]]: ...
    def to_numeric(self, errors: str = ...) -> "ColumnCollection": ...
